version: "3.5"

services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
    ports:
      - 5432:5432

  mail:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025

  keycloak:
    image: quay.io/keycloak/keycloak:18.0
    command: start-dev --import-realm -Dkeycloak.profile.feature.token_exchange=enabled -Dkeycloak.profile.feature.admin_fine_grained_authz=enabled --spi-theme-static-max-age=-1 --spi-theme-cache-themes=false --spi-theme-cache-templates=false
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
      - KC_FEATURES=token-exchange
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://db:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
      - KC_HOSTNAME=localhost
    volumes:
      - ./providers:/opt/keycloak/providers
      - ./import:/opt/keycloak/data/import
    ports:
      - 8080:8080
      - 8443:8443
    depends_on:
      - db
